name: crowd_sound
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2
  rive: ^0.12.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  

flutter:
  uses-material-design: true

  fonts:
    - family: PoiretOne
      fonts:
        - asset: assets/fonts/PoiretOne-Regular.ttf
    - family: HookedUp
      fonts:
        - asset: assets/fonts/hooked up 101.ttf
    - family: LibreBarcode
      fonts:
      - asset: assets/fonts/LibreBarcode128Text-Regular.ttf

  assets:
    - assets/images/
    - assets/riveAssets/
