name: crowd_sound
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  audioplayers: ^5.2.1
  bottom_sheet: ^4.0.4
  carousel_slider: ^4.2.1
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_map: ^7.0.2
  geolocator: ^11.1.0
  provider: ^6.1.2
  rive: ^0.12.3
  sliding_up_panel: ^2.0.0+1
  story: ^1.1.0
  video_player: ^2.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  

flutter:
  uses-material-design: true

  fonts:
    - family: PoiretOne
      fonts:
        - asset: assets/fonts/PoiretOne-Regular.ttf
    - family: HookedUp
      fonts:
        - asset: assets/fonts/hooked up 101.ttf
    - family: LibreBarcode
      fonts:
      - asset: assets/fonts/LibreBarcode128Text-Regular.ttf

  assets:
    - assets/images/
    - assets/riveAssets/
    - assets/audio/
    - assets/videos/
