name: database_repository
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  
  shared_preferences: ^2.3.2
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  crypto: ^3.0.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  

flutter:
  uses-material-design: true

  # fonts:
  #   - family: PoiretOne
  #     fonts:
  #       - asset: assets/fonts/PoiretOne-Regular.ttf
  #   - family: HookedUp
  #     fonts:
  #       - asset: assets/fonts/hooked up 101.ttf
  #   - family: LibreBarcode
  #     fonts:
  #     - asset: assets/fonts/LibreBarcode128Text-Regular.ttf

  # assets:
  #   - assets/images/
  #   - assets/riveAssets/
  #   - assets/audio/
  #   - assets/videos/
